### ISSUE TITLE
ColumnView Example

### ISSUE THREAD

**Issue by greenfuse** [timlau/gtk4_examples#1]
Hi Tim,

I have found your examples very useful. It was difficult to get a handle on the new list models in gtk4 until I discovered your code. Much appreciated, thank you.  

One small issue with main.py in the ColumnView example is that the color column displays fruit. Easily tweaked with the following:

line 32
```
#label.set_label(obj.fruit)
label.set_label(obj.color)
```

line 59 
```
#color_factory.connect("bind", bind_fruit)
color_factory.connect("bind", bind_color)
```

Your examples helped me with what I needed to make - a list with tree expansion and more than one column. If you are interested, my example of that is [here](https://github.com/greenfuse/Examples/blob/main/gtk4_tree_columns.py).

David

**Comment by timlau** [comment]
Thanks for the feedback and happy that you could use the examples, it was the whole idea.
I have fixed the code, so the color column is showing the color.
Checked your examples, they look nice
